### PR TITLE
CDH-15624: Whirr-CM to support YARN

### PR DESCRIPTION
**Pull request by ggear**

### CODE REVIEW

**Comment by rgabo** [comment]
@ggear this looks great, thanks for contributing this. Just to confirm, before I pull this into our own fork and compile it, you have tested this against whirr-cdh5.0.0-beta-2 (https://github.com/cloudera/whirr/tree/cdh5-0.8.2_5.0.0b2), right?

I can't seem to get a working cluster out of whirr 5.0.0b2 and the sample properties file, not even MRv1 with CM (`cm-ec2.properties`) or YARN (based on https://www.cloudera.com/content/cloudera-content/cloudera-docs/CDH5/latest/CDH5-Installation-Guide/cdh5ig_topic_22_4.html).

**Comment by abayer** [comment]
We need to do a fair amount of work on Whirr for C5 - hoping to get that done in time for CDH5.0.0 GA. =)

**Comment by rgabo** [comment]
@abayer thanks for the update and merging this pull request. baby steps... ;)

**Comment by ggear** [comment]
To confirm, this patch was tested with CMBeta2 and CDH4.5/CDH5Beta2 as per the integration tests:

https://github.com/cloudera/whirr-cm/blob/master/src/test/java/com/cloudera/whirr/cm/integration/CmServerSmokeSuiteIT.java#L14

**Pull request merged**
