### PR TITLE
Graham patch for CDH-11874

### PR DESCRIPTION
**Pull request by ggear**
Complete:
- Implement async console progress feedback during boostrap and configure phases

Todo:
- Implement quiet mode leveraging WHIRR-722 (https://issues.apache.org/jira/browse/WHIRR-722)

### CODE REVIEW

**Comment by abayer** [comment]
So does this need to be built against a version of Whirr with https://issues.apache.org/jira/browse/WHIRR-722 committed in it?

**Comment by ggear** [comment]
No, although the next iteration of this patch will require that.

**Comment by abayer** [comment]
'k - want me to merge this in, then?

**Comment by ggear** [comment]
Yes please!

**Comment by abayer** [comment]
Done. =)

**Pull request merged**
