### PR TITLE
CDH-11359: Provide whirr-cm interactive command line shell

### PR DESCRIPTION
**Pull request by ggear**
First pass whirr-cm shell implementation, providing client download, host query and service status

### CODE REVIEW

**Comment by abayer** [comment]
Couple questions in re: the shell - why not do it as whirr Commands? Or if you plan to go more full-featured, something Karaf-ish, like the jclouds cli? (https://github.com/jclouds/jclouds-cli)

**Comment by ggear** [comment]
I wanted to maintain separation between the the CM API classes and the Whirr classes in whirr-cm (ie com.cloudera.whirr.cm.api.\* and com.cloudera.whirr.cm.*) so that the CM API packages remain as an independent example we can point to and allow a simple refactoring into its own module in the future. This, along with not wanting to pollute whirr with too many whirr-cm concerns, is why I chose not to implement as whirr commands.

This initial implementation provides a single command script only, but is easily extended to shell like capability (this is the intention). This has been sufficient to meet my initial client download needs. Thanks for the pointer to Karaf/jclouds, I was not aware of this, I will assess how much this buys me over the initial naive implementation, I suspect it could be very useful.

**Comment by abayer** [comment]
Well, you can use Whirr commands entirely within whirr-cm, I think. I could be wrong, though.

**Comment by ggear** [comment]
After looking into this, I can see this is indeed possible so I will adapt the patch to the Whirr Command structure.

**Comment by abayer** [comment]
woot! Thanks! On a sidenote, there'd definitely be some value in a non-Whirr-specific CLI for CM, but that's probably a whole separate bucket of worms. =)

**Comment by ggear** [comment]
OK, I have just pushed this feature branch with a significant package and class refactor to suit the Whirr Command architecture - this was some necessary housekeeping and should help the codebase's growth in the future.

I have pruned all the standalone script/shell code and put in place holders for the command infrastructure so suggest we merge this pull to allow easy parallel streams of development.

Otherwise happy to continue to work on this pull, but be aware the final drop is some time off.

**Comment by abayer** [comment]
If what's there in your pull request doesn't break any existing functionality, I say hey, let's go with it.

**Comment by ggear** [comment]
Yep, all exiting functionality works

**Comment by abayer** [comment]
Then merged it shall be!

**Pull request merged**
